### ISSUE TITLE
How to sanitize html?

### ISSUE THREAD

**Issue by nikhildaga** [mpowaga/meteor-autoform-summernote#13]
In readme, you have mentioned 
" Remember to sanitize the HTML on the server!"

Can you please give me an example of how to do it?

I am inserting docs in collection using yogiben:admin.

Thanks.

**Comment by jimmiebtlr** [comment]
meteor add djedi:sanitize-html

On the server in a before hook sanatize it

    autoValue: function(){
      if( Meteor.isServer ){
        return sanitizeHtml( this.value );
      }else{
        return this.value;
      }
    },

**Comment by nikhildaga** [comment]
Thank you @jimmiebtlr :) . Its clear now.

**Comment by acomito** [comment]
Can you provide a quick example of how to sanitize with this package? Autovalue is not where you would put it if you were using summer-note in an autoform correct?

It seems other people are confused as well. This person (link below) is trying to put the allowed values into the simpleschema's summer-note settings object , but it seems like the sanatize call has to happen in a method? That's assuming your autoform is submitted and updated using a method? 

SO below:

http://stackoverflow.com/questions/36240098/sanatize-html-on-server-in-schema
