### ISSUE TITLE
type image file TIF can't insert

### ISSUE THREAD

**Issue by YouSour** [mpowaga/meteor-autoform-summernote#19]
hi , i'm using summernote now , i have some problem with insert image type TIF , i can't insert it . have any idea about this problem ? thank for advance !!!

**Comment by thearabbit** [comment]
I have the same problem (TIF Pic file).

**Comment by mpowaga** [comment]
Unfortunately TIF files are not supported. See related [issue](https://github.com/summernote/summernote/issues/1444).

**Comment by YouSour** [comment]
ok , thank you for info ! :)
