### ISSUE TITLE
$editor.code is not a function

### ISSUE THREAD

**Issue by chongwang87** [mpowaga/meteor-autoform-summernote#20]
After update summernote to latest version 0.7.0, above error message appear.

**Comment by dhrubins** [comment]
Same here

Work around: change version constraints on summernote:standalone / summernote:summernote to 0.6.14

**Comment by theodorDiaconu** [comment]
Same here. changing to 0.6.14 works.

**Comment by abeaudoin2013** [comment]
Where specifically would I change version constraints? Thanks.

**Comment by abeaudoin2013** [comment]
I was able to avoid this issue with a comment I found on a yogiben/meteor-admin issue:

https://github.com/yogiben/meteor-admin/issues/11#issuecomment-60520141

I believe the creation of this package was sparked from this conversation.
