### ISSUE TITLE
field is not populated reactively

### ISSUE THREAD

**Issue by sf-wind** [mpowaga/meteor-autoform-summernote#5]
When I "update" an autoform, the original form content is automatically populated. In my case, meteor usually subscribes a subset of the fields of the form. When the form is displayed, the client then subscribe all fields of the form. In this case, the form is rendered twice, once only showing a subset of fields populated, then it should show all fields populated. However, none of the summernote fields in the form are populated if it is subscribed in the second time. But all other non-summernote fields are still populated even if they are subscribed in the second time. 

This is an issue with summernote fields?

**Comment by bmx269** [comment]
I am having this same issue, I mean if I have multiple forms on the same page, the form values are not shown correctly. I thought it was only me. I can not solve at this moment.

**Comment by vrecluse** [comment]
Same here.

**Comment by mpowaga** [comment]
This issue is very likely to be solved with 0.4.0 version.

**Comment by benjick** [comment]
I think I have the same error, you think this will be solved too @mpowaga?

```javascript
Router.route('/admin/page/:page', {
	name: 'adminEditPage',
	data: function () {
		var data = Pages.findOne({_id: this.params.page});
		console.log(data)
		return data;
	}
});
```

When going to another page in the same route (another `_id`) all fields are updated except for the summernote field

**Comment by benjick** [comment]
Works great! Cheers!

**Comment by benjick** [comment]
Found another bug, if you have "Code View" up it's still not reactive
