### ISSUE TITLE
Update to autoform 5.0.0?

### ISSUE THREAD

**Issue by lucatros** [mpowaga/meteor-autoform-summernote#7]
Any chance on updating it to autoform 5? 
If you just update the api.use section I can test it and confirm everything is working.

Thanks!

**Comment by gdon** [comment]
+1 here.
I need to update to Autoform 5.x.

Thank you!!

**Comment by lucatros** [comment]
If you really need to update to Autoform 5.x you can just add the summernote package manually. 

1. Just create a package folder
2. copy ````meteor-autoform-summernote```` into the folder
3. change ````api.use('aldeed:autoform@4.0.0 || 5.0.0');```` on ````package.js````
4. add ````meteor-autoform-summernote```` manualy to ````./meteor/packages````

That's what I did with this and other packages and seems to work OK. Just note that there are some known bugs on Autoform 5.x so you might want to hold until they are fixed.

**Comment by gdon** [comment]
Hi lucatros.  
Ok,  I will do that. 

Thank you!!

**Comment by shkomg** [comment]
+1 created a pull request for this
