### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by adim86** [mpowaga/meteor-autoform-summernote#9]
Hi, After implementing summernote using the instructions in the README I am getting the error above when I try to submit the form. When I click on the error in the console, this function appears

```
AutoForm.addInputType('summernote', {
	template: 'afSummernote',
	valueOut: function() {
		return this.code();  (An 'x' Shows up on this line as the offender)
	}
});
```

I use Autoform 5.1.2

**Comment by mpowaga** [comment]
@adim86 Can you check with the newest version 0.4.0?
